---
kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
image:
  registry: "insecure.docker.registry.local:80/docker.io"
  repository: "bitnami/spark"
  tag: "3.2.1-debian-10-r78"
  pullPolicy: "IfNotPresent"
  pullSecrets: []
worker:
  replicaCount: 2
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
  hostname: "spark.local"
  path: "/?(.*)"
  pathType: "ImplementationSpecific"
  tls: false
metrics:
  enabled: false
