image:
  registry: insecure.docker.registry.local:80/docker.io
  repository: dpage/pgadmin4
  tag: "6.11"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  portName: http
serviceAccount:
  create: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: self-signed-issuer
  hosts:
    - host: pgadmin4.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]
env:
  email: pgadmin@geekcity.tech
  password: pgadmin
persistentVolume:
  enabled: false

