---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.1.1
    helm:
      releaseName: traefik
      valuesObject:
        image:
          registry: m.daocloud.io/docker.io
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: "traefik"
        ingressRoute:
          enabled: false
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: false
            allowExternalNameServices: false
            allowEmptyServices: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: false
            allowEmptyServices: true
        ports:
          web:
            port: 8000
            targetPort: web
            protocol: TCP
            nodePort: 32080
          websecure:
            port: 8443
            targetPort: websecure
            protocol: TCP
            nodePort: 32443
        service:
          enabled: true
          type: NodePort
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 1Gi
        env:
          - name: ALICLOUD_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: traefik-aliyun-dns-credentials
                key: access-key
          - name: ALICLOUD_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: traefik-aliyun-dns-credentials
                key: secret-key
          - name: ALICLOUD_REGION_ID
            value: "cn-hangzhou"
        certificatesResolvers:
          letsencrypt:
            acme:
              email: ben.wangz@foxmail.com
              storage: /data/acme.json
              dnsChallenge:
                provider: alidns
                delayBeforeCheck: 30
                resolvers:
                  - "223.5.5.5:53"
                  - "223.6.6.6:53"
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`dashboard.traefik.dev.geekcity.tech`)
            services:
              - name: api@internal
                kind: TraefikService
            entryPoints:
              - websecure
            tls:
              certResolver: letsencrypt
              domains:
                - main: dashboard.traefik.dev.geekcity.tech
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
