---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-demos-gaia3
spec:
  image: docker.io/wangz2019/flink-demos-gaia3:latest
  podTemplate:
    spec:
      containers:
      - name: flink-main-container
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: S3_SCHEMA
          value: http
        - name: S3_HOST
          value: minio.storage
        - name: S3_PORT
          value: "9000"
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: rootUser
        - name: S3_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: rootPassword
        - name: S3_BUCKET
          value: flink-demos-gaia3
        - name: CHECKPOINT_INTERVAL
          value: "10000"
        - name: URL_LIMIT
          value: "10"
  flinkVersion: v1_19
  ingress:
    template: "flink.k8s.io/{{namespace}}/{{name}}(/|$)(.*)"
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca-issuer
      nginx.ingress.kubernetes.io/rewrite-target: /$2
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    s3.path.style.access: "true"
    s3.endpoint: your-endpoint
    s3.access-key: your-access-key
    s3.secret-key: your-s3-secret-key
  serviceAccount: flink
  jobManager:
    resource:
      memory: 1024m
      cpu: 0.5
  taskManager:
    resource:
      memory: 1024m
      cpu: 0.5
  job:
    jarURI: local:///app/flink-application.jar
    parallelism: 2
    entryClass: tech.geekcity.flink.demos.gaia3.LoadIntoS3
    args: []
  mode: native
