externalURL: core.harbor.geekcity.tech
service:
  type: ingress
  tls:
    enabled: false
ingress:
  enabled: true
  certManager: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: self-signed-issuer
  hosts:
    core: core.harbor.geekcity.tech
    notary: notary.harbor.geekcity.tech
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: standard
      size: 4Gi
    jobservice:
      storageClass: standard
      size: 1Gi
    chartmuseum:
      storageClass: standard
      size: 1Gi
    trivy:
      storageClass: standard
      size: 2Gi
volumePermissions:
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r206
    pullPolicy: IfNotPresent
nginxImage:
  registry: localhost:5000/docker.io
  repository: bitnami/nginx
  tag: 1.21.3-debian-10-r20
  pullPolicy: IfNotPresent
portalImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-portal
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
coreImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-core
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
jobserviceImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-jobservice
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
registryImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-registry
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
registryctlImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-registryctl
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
chartMuseumImage:
  registry: localhost:5000/docker.io
  repository: bitnami/chartmuseum
  tag: 0.13.1-debian-10-r182
  pullPolicy: IfNotPresent
clairImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-clair
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
clairAdapterImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-adapter-clair
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
notaryServerImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-notary-server
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
notarySignerImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-notary-signer
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
trivyImage:
  registry: localhost:5000/docker.io
  repository: bitnami/harbor-adapter-trivy
  tag: 2.3.3-debian-10-r0
  pullPolicy: IfNotPresent
postgresql:
  persistence:
    enabled: true
    storageClass: standard
    size: 4Gi
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/postgresql
    tag: 11.13.0-debian-10-r40
  volumePermissions:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/bitnami-shell
      tag: 10-debian-10-r200
      pullPolicy: IfNotPresent
  metrics:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/postgres-exporter
      tag: 0.10.0-debian-10-r68
      pullPolicy: IfNotPresent
redis:
  architecture: standalone
  master:
    persistence:
      enabled: true
      storageClass: standard
      size: 2Gi
  replica:
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: standard
      size: 2Gi
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/redis
    tag: 6.2.5-debian-10-r63
    pullPolicy: IfNotPresent
  sentinel:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/redis-sentinel
      tag: 6.2.5-debian-10-r63
      pullPolicy: IfNotPresent
  metrics:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/redis-exporter
      tag: 1.27.1-debian-10-r4
      pullPolicy: IfNotPresent
  volumePermissions:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/bitnami-shell
      tag: 10-debian-10-r203
      pullPolicy: IfNotPresent
  sysctl:
    image:
      registry: localhost:5000/docker.io
      repository: bitnami/bitnami-shell
      tag: 10-debian-10-r203
      pullPolicy: IfNotPresent
