image:
  registry: localhost:5000/docker.io
  repository: bitnami/minio
  tag: 2021.9.18-debian-10-r0
  pullPolicy: IfNotPresent
clientImage:
  registry: localhost:5000/docker.io
  repository: bitnami/minio-client
  tag: 2021.9.2-debian-10-r17
containerPorts:
  api: 9000
  console: 9001
sidecars: [ ]
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hostname: web.minio.local
  path: /?(.*)
  tls: false
apiIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hostname: api.minio.local
  path: /?(.*)
  tls: false
persistence:
  enabled: true
  storageClass: standard
  size: 8Gi
volumePermissions:
  enabled: false
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r198
    pullPolicy: IfNotPresent
    pullSecrets: [ ]
