---
primary:
  persistence:
    storageClass: rook-cephfs-01
    size: 468Mi
image:
  registry: localhost:5000/docker.io
  repository: bitnami/mariadb
  tag: 10.5.12-debian-10-r0
  pullPolicy: IfNotPresent
volumePermissions:
  registry: localhost:5000/docker.io
  repository: bitnami/bitnami-shell
  tag: 10-debian-10-r153
  pullPolicy: Always
metrics:
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/mysqld-exporter
    tag: 0.13.0-debian-10-r56
    pullPolicy: IfNotPresent
