---
image:
  repository: "localhost:5000/docker.io/rook/ceph"
  tag: "v1.7.3"
  pullPolicy: "IfNotPresent"
crds:
  enabled: true
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
logLevel: "INFO"
csi:
  cephcsi:
    image: "localhost:5000/docker.io/quay.io/cephcsi/cephcsi:v3.4.0"
  registrar:
    image: "localhost:5000/docker.io/k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0"
  provisioner:
    image: "localhost:5000/docker.io/k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2"
  snapshotter:
    image: "localhost:5000/docker.io/k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1"
  attacher:
    image: "localhost:5000/docker.io/k8s.gcr.io/sig-storage/csi-attacher:v3.2.1"
  resizer:
    image: "localhost:5000/docker.io/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0"
  volumeReplication:
    enabled: false
    image: "localhost:5000/docker.io/quay.io/csiaddons/volumereplication-operator:v0.1.0"
