---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-connectors-s3-with-parquet-demo
spec:
  image: docker.io/wangz2019/flink-connectors-s3-with-parquet-demo:latest
  podTemplate:
    spec:
      containers:
      - name: flink-main-container
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: S3_BUCKET
          value: flink-connectors-s3-with-parquet-demo
        - name: S3_PATH
          value: sink-to-s3-with-parquet
        - name: CHECKPOINT_INTERVAL
          value: "10000"
        - name: ENABLE_BUILT_IN_PLUGINS
          value: flink-s3-fs-hadoop-1.19.0.jar
        - name: FILESYSTEM_SCHEMA
          value: s3
  flinkVersion: v1_19
  ingress:
    template: "flink.k8s.io/{{namespace}}/{{name}}(/|$)(.*)"
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca-issuer
      nginx.ingress.kubernetes.io/rewrite-target: /$2
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    s3.path.style.access: "true"
  serviceAccount: flink
  jobManager:
    resource:
      memory: 1024m
      cpu: 0.5
  taskManager:
    resource:
      memory: 1024m
      cpu: 0.5
  job:
    jarURI: local:///app/flink-application.jar
    parallelism: 2
    entryClass: tech.geekcity.flink.connectors.s3.parquet.SinkToS3WithParquet
    args: []
  mode: native
