---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tidb-cluster-backup-pvc
  namespace: tidb-cluster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
