---
apiVersion: pingcap.com/v1alpha1
kind: Restore
metadata:
  name: restore-tidb-cluster-basic-full-1748228371
  namespace: tidb-cluster
spec:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  restoreMode: snapshot
  backupType: full
  toolImage: m.daocloud.io/docker.io/pingcap/br:v8.5.0
  br:
    cluster: basic
    clusterNamespace: tidb-cluster
    logLevel: info
    concurrency: 4
    # rateLimit: 0
    # options:
    # - --lastbackupts=420134118382108673
  local:
    prefix: tidb-cluster/basic/full/1748228371
    volume:
      name: backup
      persistentVolumeClaim:
        claimName: tidb-cluster-backup-pvc
    volumeMount:
      name: backup
      mountPath: /backup
