apiVersion: v1
kind: ServiceAccount
metadata:
  name: tidb-backup-manager
  namespace: tidb-cluster

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tidb-backup-manager-role
  namespace: tidb-cluster
rules:
- apiGroups: ["pingcap.com"]
  resources: ["backups"]
  verbs:
    - list
    - get
    - update
    # - create
    # - delete
    # - patch
    # - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tidb-backup-manager-rolebinding
  namespace: tidb-cluster
subjects:
- kind: ServiceAccount
  name: tidb-backup-manager
  namespace: tidb-cluster
roleRef:
  kind: Role
  name: tidb-backup-manager-role
  apiGroup: rbac.authorization.k8s.io
