image:
  repository: registry
  tag: 2.7.1
ingress:
  enabled: false
persistence:
  enabled: false
extraVolumeMounts:
  - name: auth
    mountPath: /auth
    readOnly: true
extraVolumes:
  - name: auth
    secret:
      secretName: docker-registry-secret
      items:
        - key: htpasswd
          path: htpasswd
