apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tidb-operator-crd
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true 
  project: default
  source:
    repoURL: https://gitee.com/ben-wangz-mirror/tidb-operator.git
    targetRevision: v1.6.1
    path: manifests/crd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
