---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tidb-operator
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.pingcap.org/
    chart: tidb-operator
    targetRevision: v1.6.1
    helm:
      releaseName: tidb
      valuesObject:
        timezone: Asia/Shanghai
        operatorImage: m.daocloud.io/docker.io/pingcap/tidb-operator:v1.6.1
        tidbBackupManagerImage: m.daocloud.io/docker.io/pingcap/tidb-backup-manager:v1.6.1
        scheduler:
          kubeSchedulerImageName: m.daocloud.io/registry.k8s.io/kube-scheduler
        advancedStatefulset:
          image: m.daocloud.io/pingcap/advanced-statefulset:v0.7.0
  destination:
    server: https://kubernetes.default.svc
    namespace: tidb-admin
