---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://ben-wangz.github.io/helm-chart-mirror/charts
    chart: cert-manager
    targetRevision: 1.13.3
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        image:
          repository: quay.io/jetstack/cert-manager-controller
          tag: v1.13.3
        webhook:
          image:
            repository: quay.io/jetstack/cert-manager-webhook
            tag: v1.13.3
        cainjector:
          image:
            repository: quay.io/jetstack/cert-manager-cainjector
            tag: v1.13.3
        acmesolver:
          image:
            repository: quay.io/jetstack/cert-manager-acmesolver
            tag: v1.13.3
        startupapicheck:
          image:
            repository: quay.io/jetstack/cert-manager-ctl
            tag: v1.13.3
  destination:
    server: https://kubernetes.default.svc
    namespace: basic-components
