---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "cert-manager"
spec:
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
  project: "default"
  source:
    repoURL: "https://ben-wangz.github.io/helm-chart-mirror/charts"
    chart: "cert-manager"
    targetRevision: "1.13.3"
    helm:
      releaseName: "cert-manager"
      values: "installCRDs: true\nimage:\n  repository: m.daocloud.io/quay.io/jetstack/cert-manager-controller\n\
        \  tag: v1.13.3\nwebhook:\n  image:\n    repository: m.daocloud.io/quay.io/jetstack/cert-manager-webhook\n\
        \    tag: v1.13.3\ncainjector:\n  image:\n    repository: m.daocloud.io/quay.io/jetstack/cert-manager-cainjector\n\
        \    tag: v1.13.3\nacmesolver:\n  image:\n    repository: m.daocloud.io/quay.io/jetstack/cert-manager-acmesolver\n\
        \    tag: v1.13.3\nstartupapicheck:\n  image:\n    repository: m.daocloud.io/quay.io/jetstack/cert-manager-ctl\n\
        \    tag: v1.13.3\n"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "basic-components"
