---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yugabyte-db
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.yugabyte.com
    chart: yugabyte
    targetRevision: 2.19.3
    helm:
      releaseName: yugabyte-db
      values: |
        Image:
          repository: "yougabytedb/yougabyte"
        storage:
          ephemeral: true
        enableLoadBalancer: false
        serviceEndpoints:
          - name: "yb-master-ui"
            type: ClusterIP
            app: "yb-master"
            ports:
              http-ui: 7000
          - name: "yb-tserver-service"
            type: ClusterIP
            app: "yb-tserver"
            ports:
              tcp-yql-port: 9042
              tcp-yedis-port: 6379
              tcp-ysql-port: 5433
        resource:
          master:
            requests:
              cpu: 0.25
              memory: 0.5Gi
          tserver:
            requests:
              cpu: 0.25
              memory: 0.5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: database
