---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "yugabyte-db"
spec:
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
  project: "default"
  source:
    repoURL: "https://charts.yugabyte.com"
    chart: "yugabyte"
    targetRevision: "2.19.3"
    helm:
      releaseName: "yugabyte-db"
      values: "Image:\n  repository: \"yougabytedb/yougabyte\"\nstorage:\n  ephemeral:\
        \ true\nenableLoadBalancer: false\nserviceEndpoints:\n  - name: \"yb-master-ui\"\
        \n    type: ClusterIP\n    app: \"yb-master\"\n    ports:\n      http-ui:\
        \ 7000\n  - name: \"yb-tserver-service\"\n    type: ClusterIP\n    app: \"\
        yb-tserver\"\n    ports:\n      tcp-yql-port: 9042\n      tcp-yedis-port:\
        \ 6379\n      tcp-ysql-port: 5433\nresource:\n  master:\n    requests:\n \
        \     cpu: 0.25\n      memory: 0.5Gi\n  tserver:\n    requests:\n      cpu:\
        \ 0.25\n      memory: 0.5Gi\n"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "application"
