apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.13.1
    helm:
      releaseName: basic-cert-manager
      values: |
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: basic-components
