---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-search
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: elasticsearch
    targetRevision: 19.21.2
    helm:
      releaseName: elastic-search
      values: |
        global:
          kibanaEnabled: false
        clusterName: elastic
        image:
          registry: docker.io
          pullPolicy: IfNotPresent
        security:
          enabled: false
        service:
          type: ClusterIP
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: self-signed-ca-issuer
            nginx.ingress.kubernetes.io/rewrite-target: /$1
          hostname: elastic-search.dev.geekcity.tech
          ingressClassName: nginx
          path: /?(.*)
          tls: true
        master:
          masterOnly: true
          replicaCount: 2
          persistence:
            enabled: false
        data:
          replicaCount: 2
          persistence:
            enabled: false
        coordinating:
          replicaCount: 2
        ingest:
          enabled: true
          replicaCount: 2
          service:
            enabled: false
            type: ClusterIP
          ingress:
            enabled: false
        metrics:
          enabled: false
          image:
            registry: docker.io
            pullPolicy: IfNotPresent
        volumePermissions:
          enabled: false
          image:
            registry: docker.io
            pullPolicy: IfNotPresent
        sysctlImage:
          enabled: true
          registry: docker.io
          pullPolicy: IfNotPresent
        kibana:
          elasticsearch:
            hosts:
              - '{{ include "elasticsearch.service.name" . }}'
            port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
  destination:
    server: https://kubernetes.default.svc
    namespace: application
