---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb
    targetRevision: 16.3.2
    helm:
      releaseName: mariadb
      values: |
        architecture: standalone
        auth:
          database: geekcity
          username: ben.wangz
          existingSecret: mariadb-credentials
        primary:
          extraFlags: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
          persistence:
            enabled: false
        secondary:
          replicaCount: 1
          persistence:
            enabled: false
        image:
          registry: docker.io
          pullPolicy: IfNotPresent
        volumePermissions:
          enabled: false
          image:
            registry: docker.io
            pullPolicy: IfNotPresent
        metrics:
          enabled: true
          image:
            registry: docker.io
            pullPolicy: IfNotPresent
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9104"
          serviceMonitor:
            enabled: true
            namespace: monitor
            jobLabel: mariadb
            interval: 30s
            labels:
              release: kube-prometheus-stack
          prometheusRule:
            enabled: true
            namespace: monitor
            additionalLabels:
              release: kube-prometheus-stack
            rules:
            - alert: MariaDB-Down
              expr: absent(up{job="mariadb"} == 1)
              for: 5m
              labels:
                severity: warning
                service: mariadb
              annotations:
                summary: MariaDB instance is down
                message: 'MariaDB instance {{ `{{` }} $labels.instance {{ `}}` }} is down'
  destination:
    server: https://kubernetes.default.svc
    namespace: database
