image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.23.3-debian-11-r33
  pullPolicy: IfNotPresent
  pullSecrets: [ ]
extraVolumes:
  - name: git-ssh-key-vol
    secret:
      secretName: git-ssh-key-secret
      items:
        - key: id_rsa
          path: id_rsa
          mode: 0600
service:
  type: ClusterIP
cloneStaticSiteFromGit:
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.39.2-debian-11-r9
  enabled: true
  repository: git@github.com:ben-wangz/blog.git
  branch: main
  interval: 60
  extraVolumeMounts:
    - name: git-ssh-key-vol
      mountPath: /root/.ssh
  extraEnvVars:
    - name: GIT_SSH_COMMAND
      value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  gitSync:
    command:
      - /bin/bash
      - -ec
      - |
        [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh"
        while true; do
            cd /app && git pull origin {{ .Values.cloneStaticSiteFromGit.branch }} || echo WARNNING: skiping failed pull
            sleep {{ .Values.cloneStaticSiteFromGit.interval }}
        done
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: alidns-webhook-letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hostname: blog.geekcity.tech
  path: /?(.*)
  tls: true
