common:
  setPVOwnerRef: true
classes:
  - name: rook-monitor
    hostDir: /data/local-static-provisioner/rook-monitor
    volumeMode: Filesystem
    fsType: ext4
    namePattern: "*"
    blockCleanerCommand:
      - "/scripts/shred.sh"
      - "2"
    storageClass: true
daemonset:
  image: localhost:5000/docker.io/k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0