apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-application
spec:
  project: default
  sources:
  - repoURL: https://charts.loft.sh
    chart: vcluster-k8s
    targetRevision: 0.16.2
    helm:
      releaseName: basic-vcluster
      values: |
        etcd:
          replicas: 3
          className: nfs-external
        controller:
          replicas: 2
        vcluster:
          # choose k3s version
          image: rancher/k3s:v1.23.5-k3s1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: basic-vcluster
