apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed-issuer
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
spec:
  secretName: self-signed-ca-secret
  duration: 2160h
  renewBefore: 360h
  isCA: true
  commonName: self-signed-ca.geekcity.tech
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - self-signed-ca.geekcity.tech
  issuerRef:
    name: self-signed-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: self-signed-ca-secret