apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:
  clusters:
    - name: basic
  prometheus:
    baseImage: m.daocloud.io/docker.io/prom/prometheus
    version: v2.27.1
  grafana:
    baseImage: m.daocloud.io/docker.io/grafana/grafana
    version: 7.5.11
    usernameSecret:
      name: basic-grafana-credentials
      key: username
    passwordSecret:
      name: basic-grafana-credentials
      key: password
    ingress:
      hosts:
        - tidb-monitor.dev.geekcity.tech
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/issuer: self-signed-issuer
      tls:
        - hosts:
            - tidb-monitor.dev.geekcity.tech
          secretName: tidb-monitor.dev.geekcity.tech-tls
  initializer:
    baseImage: m.daocloud.io/docker.io/pingcap/tidb-monitor-initializer
    version: v8.5.0
  reloader:
    baseImage: m.daocloud.io/docker.io/pingcap/tidb-monitor-reloader
    version: v1.0.1
  prometheusReloader:
    baseImage: m.daocloud.io/quay.io/prometheus-operator/prometheus-config-reloader
    version: v0.49.0
  imagePullPolicy: IfNotPresent
