---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "ingress-nginx"
spec:
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
  project: "default"
  source:
    repoURL: "https://ben-wangz.github.io/helm-chart-mirror/charts"
    chart: "ingress-nginx"
    targetRevision: "4.9.0"
    helm:
      releaseName: "ingress-nginx"
      values: "controller:\n  image:\n    registry: m.daocloud.io\n    image: registry.k8s.io/ingress-nginx/controller\n\
        \    tag: \"v1.9.5\"\n    pullPolicy: IfNotPresent\n  service:\n    enabled:\
        \ true\n    type: NodePort\n    nodePorts:\n      http: 32080\n      https:\
        \ 32443\n      tcp:\n        8080: 32808\n  admissionWebhooks:\n    enabled:\
        \ true\n    patch:\n      enabled: true\n      image:\n        registry: m.daocloud.io\n\
        \        image: registry.k8s.io/ingress-nginx/kube-webhook-certgen\n     \
        \   tag: v20231011-8b53cabe0\n        pullPolicy: IfNotPresent\ndefaultBackend:\n\
        \  enabled: false\n"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "basic-components"
