---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  labels:
    app: "test-prometheus"
    release: "test-prometheus"
    app.kubernetes.io/instance: "test-prometheus"
    app.kubernetes.io/part-of: "test-prometheus"
    monitor-service: "test-prometheus"
  name: "test-prometheus"
spec:
  endpoints:
  - port: "metrics"
  namespaceSelector:
    matchNames:
    - "test"
  selector:
    matchLabels:
      app.kubernetes.io/component: "primary"
      app.kubernetes.io/name: "mariadb"
      app.kubernetes.io/instance: "mariadb-for-test"
