apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alidns-webhook-application
  namespace: {{ .Values.spec.namespace }}
spec:
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: https://devmachine-fr.github.io/cert-manager-alidns-webhook
    chart: alidns-webhook
    targetRevision: 0.7.0
    helm:
      releaseName: alidns-webhook
      values: |
        groupName: dev.geekcity.tech
        certManager:
          namespace: basic-components
          serviceAccountName: cert-manager
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}