apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: {{ .Values.spec.namespace }}
spec:
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.13.1
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
