---
image:
  repository: "insecure.docker.registry.local:80/ghcr.io/helm/chartmuseum"
  tag: "v0.13.1"
  pullPolicy: "IfNotPresent"
volumePermissions:
  image:
    registry: "insecure.docker.registry.local:80/docker.io"
    repository: "bitnami/minideb"
    tag: "buster"
    pullPolicy: "IfNotPresent"
persistence:
  enabled: true
  size: "2Gi"
env:
  open:
    DISABLE_API: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "self-signed-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  hosts:
  - name: "chart.museum.local"
    path: "/?(.*)"
    tls: true
    tlsSecret: "chart.museum.local-tls"
