---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juicefs-csi
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://juicedata.github.io/charts
    chart: juicefs-csi-driver
    targetRevision: 0.28.2
    helm:
      releaseName: juicefs-csi
      valuesObject:
        image:
          repository: m.daocloud.io/docker.io/juicedata/juicefs-csi-driver
        dashboardImage:
          repository: m.daocloud.io/docker.io/juicedata/csi-dashboard
        sidecars:
          livenessProbeImage:
            repository: m.daocloud.io/registry.k8s.io/sig-storage/livenessprobe
          nodeDriverRegistrarImage:
            repository: m.daocloud.io/registry.k8s.io/sig-storage/csi-node-driver-registrar
          csiProvisionerImage:
            repository: m.daocloud.io/registry.k8s.io/sig-storage/csi-provisioner
          csiResizerImage:
            repository: m.daocloud.io/registry.k8s.io/sig-storage/csi-resizer
        imagePullSecrets: []
        mountMode: mountpod
        driverName: "csi.juicefs.com"
        jfsMountDir: /var/lib/juicefs/volume
        jfsConfigDir: /var/lib/juicefs/config
        immutable: false
        controller:
          enabled: true
          cacheClientConf: false
          replicas: 3
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
        node:
          enabled: true
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
        dashboard:
          enabled: true
          enableManager: true
          auth:
            enabled: true
            existingSecret: "juicefs-dashboard-secret"
          replicas: 1
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi
          ingress:
            enabled: true
            className: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: self-signed-ca-issuer
            hosts:
            - host: "juice-fs-dashboard.dev.geekcity.tech"
              paths:
              - path: /
                pathType: ImplementationSpecific
            tls:
            - secretName: juice-fs-dashboard.dev.geekcity.tech-tls
              hosts:
              - juice-fs-dashboard.dev.geekcity.tech
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
