---
daemonset:
  enabled: true
  envFrom: []
  extraEnvs:
  - name: "ELASTICSEARCH_HOSTS"
    value: "elasticsearch-master:9200"
  extraVolumes: []
  extraVolumeMounts: []
  filebeatConfig:
    filebeat.yml: "filebeat.inputs:\n- type: container\n  paths:\n    - /var/log/containers/*.log\n\
      \  processors:\n  - add_kubernetes_metadata:\n      host: ${NODE_NAME}\n   \
      \   matchers:\n      - logs_path:\n          logs_path: \"/var/log/containers/\"\
      \noutput.elasticsearch:\n  host: '${NODE_NAME}'\n  hosts: '${ELASTICSEARCH_HOSTS}'\n"
  maxUnavailable: 1
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "200Mi"
deployment:
  enabled: false
replicas: 1
hostPathRoot: "/var/lib"
image: "insecure.docker.registry.local:80/docker.io/docker.elastic.co/beats/filebeat"
imageTag: "7.16.3"
imagePullPolicy: "IfNotPresent"
imagePullSecrets: []
livenessProbe:
  exec:
    command:
    - "sh"
    - "-c"
    - "#!/usr/bin/env bash -e\ncurl --fail 127.0.0.1:5066\n"
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  exec:
    command:
    - "sh"
    - "-c"
    - "#!/usr/bin/env bash -e\nfilebeat test output\n"
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
managedServiceAccount: true
updateStrategy: "RollingUpdate"
