---
elasticsearchHosts: http://elasticsearch-master:9200
replicas: 1
extraEnvs:
- name: NODE_OPTIONS
  value: --max-old-space-size=1800
image: insecure.docker.registry.local:80/docker.io/docker.elastic.co/kibana/kibana
imageTag: 7.16.3
imagePullPolicy: IfNotPresent
resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
protocol: http
serverHost: 0.0.0.0
healthCheckPath: /app/kibana
kibanaConfig: {}
service:
  type: ClusterIP
  loadBalancerIP: ""
  port: 5601
  nodePort: ""
  labels: {}
  annotations: {}
  loadBalancerSourceRanges: []
  httpPortName: http
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: self-signed-issuer
  className: ""
  pathtype: ImplementationSpecific
  hosts:
  - host: kibana.local
    paths:
    - path: /
  tls:
  - secretName: kibana.local-tls
    hosts:
    - kibana.local
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
