---
apiVersion: "tekton.dev/v1beta1"
kind: "PipelineRun"
metadata:
  name: "pipelinerun-demo"
spec:
  pipelineRef:
    name: "pipeline-demo"
  podTemplate:
    hostAliases:
    - ip: "192.168.123.7"
      hostnames:
      - "insecure.docker.registry.local"
  workspaces:
  - name: "git-source"
    volumeClaimTemplate:
      spec:
        storageClassName: "standard"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  - name: "git-ssh-keys"
    secret:
      secretName: "git-ssh-key-secret"
      items:
      - key: "id_rsa"
        path: "id_rsa"
        mode: 384
      - key: "id_rsa.pub"
        path: "id_rsa.pub"
        mode: 384
