---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: clickhouse
  name: clickhouse-mysql-interface
spec:
  ports:
  - name: tcp-mysql
    port: 9004
    protocol: TCP
    targetPort: tcp-mysql
    nodePort: 32004
  selector:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/name: clickhouse
  type: NodePort
