---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgresql-tool"
  labels:
    app.kubernetes.io/name: "postgresql-tool"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "postgresql-tool"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "postgresql-tool"
    spec:
      containers:
      - name: "postgresql-tool"
        image: "insecure.docker.registry.local:80/docker.io/bitnami/postgresql:14.4.0-debian-11-r9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "postgres-password"
              name: "my-postgresql"
        - name: "TZ"
          value: "Asia/Shanghai"
        command:
        - "tail"
        args:
        - "-f"
        - "/etc/hosts"
